### ISSUE TITLE
About the implementation of TIGER

### ISSUE THREAD

**Issue by LehengTHU** [anananan116/MBGen#4]
Greetings. Your work is so wonderful and inspiring!
Could you please share the implementation of TIGER? It's hard for me to find open-source implementations for this algorithm. Thank you!

**Comment by anananan116** [comment]
Thanks for your interest in this project. We're building a comprehensive package on generative recommendations (including TIGER), and it will be released soon. Please stay tuned. I will update the readme in this repo to include the released package when it's ready.

For now, most of the components of TIGER are already in this repo. Simply changing the tokenization and quantization part would reproduce TIGER.

**Comment by LehengTHU** [comment]
Thank you! Got it!
