### ISSUE TITLE
Question About CID

### ISSUE THREAD

**Issue by tanyz0208** [anananan116/MBGen#5]
Greetings, 
       I'm currently following your project and doing some incremental research. However, I couldn't find the 'K' you used in generating CID. Could you please specify the 'K' used in each dataset? It would be really appreciated!

**Comment by tanyz0208** [comment]
I set 'K' to 8 for both datasets. The performance on 'retail' is better than that reported in the paper. However, it performed much worse on 'IJCAI'
For 'retail':
Test Loss(target): 1.3342474264000617
Recall@5(target): 0.5054655029093932
Recall@10(target): 0.5562240232751455
NDCG@5(target): 0.3856995137741414
NDCG@10(target): 0.4022674695026087

For 'IJCAI':
Test Loss(target): 1.6504856421158938
Recall@5(target): 0.08977115770969363
Recall@10(target): 0.12238667754897037
NDCG@5(target): 0.06416196183071969
NDCG@10(target): 0.07470905743668349

Am I setting the 'K' wrong? Any help from you will be really appreciated!

**Comment by anananan116** [comment]
As said in the paper, we chose k=64 for retail and k=96 for IJCAI. I'll upload the config files for reproducing the CID experiments soon.

**Comment by anananan116** [comment]
I've uploaded the configs for reproducing CID experiments. I'm closing the issue.

**Comment by tanyz0208** [comment]
Thanks for the response!!!
