### ISSUE TITLE
Retail/Taobao Source

### ISSUE THREAD

**Issue by sonngocl22** [anananan116/MBGen#6]
Dear Authors,

Thank you for your research and contributions. I was looking for the original dataset from Taobao (Retail) and found [this](https://tianchi.aliyun.com/dataset/649?lang=en-us). However, when following the same preprocessing in the paper, the numbers don't seem to match. Could you kindly let me know the original source or provider of the Retail/Taobao dataset?  Would be great if you could share the preprocessing file of the dataset as well.

Thank you in advance.

Kind regards,
Son Le

**Comment by anananan116** [comment]
Hi, thanks for your interest in this project. The original data files could be found in the link provided in readme. We followed MB-STR and used the same processed dataset published in their github [repo](https://github.com/yuanenming/mb-str). We further processed the dataset using https://github.com/anananan116/MBGen/blob/main/data/preprocessing/preprocess.py.

**Comment by sonngocl22** [comment]
Thank you a lot for your answer!
